version: '2'
catalog:
  name: "Zenko"
  version: "v1.0"
  description: "initialize"
services:
  s3:
    scale: 1
  loadbalancer:
    lb_config:
      certs: []
      config: |-
        # vc-api/os-apiのtimeoutが1200sに設定しているのでそれに合わせる
        defaults
                timeout client 1300s
                timeout server 1300s