version: '2'
catalog:
  name: "Zenko"
  version: "v1.0"
  description: "initialize"
services:
  s3:
    scale: 1
  loadbalancer:
    scale: 1
    lb_config:
       port_rules:
       - source_port: 80
         target_port: 8000
         service: s3